
apiVersion: v1
kind: Service
metadata:
    name: devopsalbert-service
spec:
    selector:
        app: devopsalbert-service
    ports:
        - port: 3000
          targetPort: 3000
          name: devopsalbert-service
          protocol: TCP
    type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: devopsalbert-service
    namespace: dev
spec:
    replicas: 1

___

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: devopsalbert-ingress
    namespace: dev
spec:
    rules:
        - host: 116.203.102.6.xip.io
          http:
              paths:
                - backend:
                    serviceName: devopsalbert-service
                    servicePort: 3000
    tls:
        - hosts:
            - 116.203.102.6.xip.io

